### ISSUE TITLE
Exercises in invisible courses can be accessed by URL

### ISSUE THREAD

**Issue by LassiHaaranen** [Aalto-LeTech/a-plus#111]
Exercises in invisible courses can be accessed with the exercise URL by a user logged in  even if the user does not have the rights to view the course.

Only login status is checked, not whether the course (and by extension, exercises) are visible to students, see: https://github.com/Aalto-LeTech/a-plus/blob/master/exercise/views.py#L33

**Comment by teemulehtinen** [comment]
Fixed and enforced by class based view hierarchy.
