### ISSUE TITLE
Course news from Noppa API

### ISSUE THREAD

**Issue by LassiHaaranen** [Aalto-LeTech/a-plus#118]
A+ should be able to fetch and show course news from the Noppa API.

For information about the API see [Noppa API specs](https://wiki.aalto.fi/download/attachments/71895449/NoppaAPI_eng.pdf?version=2&modificationDate=1352361073000&api=v2).

**Comment by teemulehtinen** [comment]
Noppa is closing down. A+ has already plugin structure for e.g. RSS. Lets reopen if new use case appears.
