### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by LassiHaaranen** [Aalto-LeTech/a-plus#123]
Maintenance mode would show students a message about system being currently under maintenance and relevant information when A+ will be online again.

**Comment by teemulehtinen** [comment]
There are 3rd party django modules to switch into maintenance mode.

**Comment by raphendyr** [comment]
This is best done using web server configuration. For example with nginx:

```
server {
  error_page 503 /static/err_503.html;
  location /static { alias /srv/a-plus/static; }
  location / {
    if (-f /srv/a-plus/maintenance) { return 503; }
    proxy_pass http://a-plus;
  }
}
```

This could be done within an upgrade script. For example, [mooc-jutut install.py](https://github.com/Aalto-LeTech/mooc-jutut/blob/2.2.1/scripts/install.py#L418) does a similar thing.
