### ISSUE TITLE
LTI integration does not comply the protocol

### ISSUE THREAD

**Issue by ttsirkia** [Aalto-LeTech/a-plus#165]
In the official LTI documentation (http://www.imsglobal.org/lti/blti/bltiv1p0/ltiBLTIimgv1p0.html), the teaching assistant role is `TeachingAssistant`. However, in A+ it is incorrectly `TA`.

**Comment by teemulehtinen** [comment]
When fixing this test that Piazza supports the correct form. Their documentation uses TA https://s3.amazonaws.com/piazza-materials/LTI-Setup/GetAProgrammerStartedWithLTI.pdf

**Comment by teemulehtinen** [comment]
It might be also useful to add a configuration option to pass the real userid or the unique hash as it currently does.

**Comment by teemulehtinen** [comment]
Now TeachingAssistant.
