### ISSUE TITLE
Installation error (mimeparse)

### ISSUE THREAD

**Issue by ihantola** [Aalto-LeTech/a-plus#182]
When following the installation instructions on Ubuntu Server 14.04 (python3 from the distro), I hit the following problem in installing mimeparse from the requirements:

```
  Complete output from command /home/aplus/venv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-_4hrrkjh/mimeparse/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpck7vu9l6pip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-_4hrrkjh/mimeparse/setup.py", line 1
      ﻿# -*- coding: utf-8 -*-
      ^
  SyntaxError: invalid character in identifier

  ----------------------------------------
  Failed building wheel for mimeparse
```

Do we need mimeparse at all? At least it's not explicitly used anywhere in a-plus codebase. Some old posts hint that the project might have been abandoned already few years ago: https://code.google.com/p/mimeparse/issues/detail?id=16

**Comment by ihantola** [comment]
At least all tests pass without mimeparse so either it should be removed from the dependencies or a test case catching this should be added.

**Comment by teemulehtinen** [comment]
The mimeparse is a requirement for Tastypie API and must be installed. However, the installation error doesn't seem to break the application. We are planning to reimplement the API using Django REST framework.
