### ISSUE TITLE
Rethink synchronous submission

### ISSUE THREAD

**Issue by Rubinous** [Aalto-LeTech/a-plus#22]
Firstly, if the response for a synchronous submission timeouts, the grader server has no chance of posting the results back to a-plus which is a shame if the grader was able to asses the submission in the end.

Secondly, the timeout for the synchronous submission can't be as long as the current 50 seconds. This potentially blocks the service, because the wsgi thread actually hangs the whole time while waiting for the response from the grader. For example, if the grader service has a bug that makes it hang and not respond ever, the thread capacity would probably get full.

Thirdly, potential wait time of 50 seconds would be annoying for the user.

One suggested solution is to make all submissions asynchronous but in case of those exercises that could be synchronous, we would poll for the result for lets say 10 seconds before informing the user that the assessment service takes unusually long.

**Comment by teemulehtinen** [comment]
Any non trivial graders must be asynchronous. Automatic polling is implemented and carried out if meta "wait" is returned.
