### ISSUE TITLE
Submissions pagination breaks search

### ISSUE THREAD

**Issue by piehei** [Aalto-LeTech/a-plus#258]
If you look at the "all submissions" of an exercise that has received more than 50 submissions, the results list page is paginated and only the first 50 results are shown.

If you make a search by name, points, or whatever, the search returns matches only from those shown submissions (the first 50). If there is a match in results numbered 51–n, the UI doesn't show it to you since the search returns results only from the shown submissions. You have to click "show all submissions" and search again.

I suggest that either the UI has to have a clear way of telling the searcher that it is showing results from the shown submissions or there should be some way to either choose "search from all" or "search from the shown results". As of now it's not very clear and it often happens that you search for something and when it returns nada results you conclude there weren't any which isn't true.

**Comment by teemulehtinen** [comment]
Filters removed from the quick 50 list.
