### ISSUE TITLE
Prevent double submissions

### ISSUE THREAD

**Issue by myrjola** [Aalto-LeTech/a-plus#301]
One student probably double clicked the submit button for an exercise, thus sending two grading requests and using up two of his limited submissions. Would it be possible to prevent submissions from the same student for a short period, say 1 minute, after each submission?

The case I'm talking about are submission IDs 1131535 and 1131536 accessed by https://plus.cs.hut.fi/os/2017/round1/round1/submissions/1131535/inspect/. I can see that both submissions are submitted during the same minute.

**Comment by teemulehtinen** [comment]
This is the first reported case of double submission so I think this is not a highest priority bug. Note that you can add an extra submission to user in the inspect view with the [+] button in the left column under submissions title.

I think the best way to fix this is to add javascript that immediately disables the submit button on click event.

**Comment by myrjola** [comment]
We now have two students that the double submission happened to. They told me that they didn't double click or in any way submit the form twice. Maybe it could be checked at least for the submissions with ID 1131535 and 1131536 that there are POSTs coming from the client for both of them. Just to make sure there is no strange bug causing the double submission.

**Comment by raphendyr** [comment]
This should be fixed in commit acd528b5e2a71fbbf3b134313dbe8134162a7b85, which disallows double clicking submit buttons on old style exercises. Chapter exercises don't contain similar problem as the submit opens dialog.
