### ISSUE TITLE
Re-submitting exercise form in submission view is not possible

### ISSUE THREAD

**Issue by Rubinous** [Aalto-LeTech/a-plus#31]
It is intuitive to try to re-submit exercise form in the submission view in cases where the submission feedback includes the original form. But the form action in that case would be the submissions url instead of exercise url and it won't be handled as the user would expect.

**Comment by teemulehtinen** [comment]
The original POST URL is given as a GET parameter now. The grader may include a POST form in the feedback for resubmitting. Of course the exercise should be designed for resubmitting.
