### ISSUE TITLE
Make TOC view clearer

### ISSUE THREAD

**Issue by piehei** [Aalto-LeTech/a-plus#336]
TOC version of the course index is a bit hard to read when you've got lots of content.

I suggest either of these two layouts to make it easier for the reader:

![screenshot 2018-06-06 at 20 43 00](https://user-images.githubusercontent.com/8404555/41055575-5f1b5d32-69ca-11e8-83d7-f490a3cb6b2f.png)
![screenshot 2018-06-06 at 20 41 42](https://user-images.githubusercontent.com/8404555/41055577-5f415154-69ca-11e8-8782-8b5041e7accb.png)

Original:

![screenshot 2018-06-06 at 20 44 56](https://user-images.githubusercontent.com/8404555/41055718-aded7076-69ca-11e8-9e50-62278696631d.png)

What do you think? Any other versions?

**Comment by raphendyr** [comment]
Huargh. I see. For the next level.

I would say the second one as the bold subtitles in the first might take the focus from the module title.
