### ISSUE TITLE
A+ frontend not waiting for grader

### ISSUE THREAD

**Issue by ghost** [Aalto-LeTech/a-plus#342]
When starting the A+ frontend together with the mooc-grader as Docker containers the A+ frontend will try to connect to the grader before it's ready to accept connections, leading to the frontend not getting any course configurations. The frontend will then hang and not attempt to reconnect, only showing the default course. Expected behaviour would be to retry acquiring a course configuration for some time before giving up on the grader. Attached docker-compose.yml to reproduce issue.

[docker-compose.txt](https://github.com/Aalto-LeTech/a-plus/files/2110213/docker-compose.txt)

**Comment by raphendyr** [comment]
This is maybe more related to docker containerisation of the A+. Not sure if the loop should be implemented in A+ management command or in the up script. I created issue on container repo too: 
https://github.com/apluslms/run-aplus-front/issues/2

I'm working on to get mooc-jutut inside a container and that includes creating better infrastructure for setting up services. Once that is done, I can redesign A+ container with nginx and real db and thus fix few other issues too.

**Comment by raphendyr** [comment]
This was fixed in run-aplus-front version 1.4.
