### ISSUE TITLE
Group submission mode in an LTI exercise breaks the course-wide exercise results page

### ISSUE THREAD

**Issue by Mankro** [Aalto-LeTech/a-plus#348]
Note: LTI exercises do not currently support group submissions, but they could be implemented in the future.

I created a few LTI exercises in a new course space (independent exercises without chapters). I enabled group submissions for one LTI exercise. I made submissions to some exercises (alone or in a group, varying between exercises). When I open the course front page (exercise results that shows the rounds with point progress bars etc.), it shows no submissions nor points, as if I had never submitted anything. However, I see the submissions and points in the exercise page.

**Comment by Mankro** [comment]
I added a normal exercise to the course and submitted to it. After that, the course front page displayed points correctly on all exercises, so there seems to be a problem if there are only LTI exercises in the course and some of them have enabled group submissions.

**Comment by raphendyr** [comment]
Sounds like the cache is not updated when LTI exercise get's an submission. In other words, is this called after lti exercise update? https://github.com/Aalto-LeTech/a-plus/blob/master/exercise/cache/points.py#L235

**Comment by raphendyr** [comment]
Feel free to add m2m_changed hook there :)
