### ISSUE TITLE
Installation instructions and requirements

### ISSUE THREAD

**Issue by pjotrsavitski** [Aalto-LeTech/a-plus#372]
Requirements seem to be wrong and pointing to a version of Django that is no longer being used **1.7 VS 1.10**.

This turns the installation process into a guessing game:https://github.com/Aalto-LeTech/a-plus/blob/master/doc/DEPLOYMENT.md

The real requirements seems to be the ones that apply to Django version 1.10. Mostly any of the Python 3.5.x releases.

**Comment by raphendyr** [comment]
Yes. Instructions are outdated. py 3.5 and up and stuff in requirements.txt.

**Comment by raphendyr** [comment]
DEPLOYMENT.md is now updated.
