### ISSUE TITLE
Is there any way to create courses without Shibolleth?

### ISSUE THREAD

**Issue by pjotrsavitski** [Aalto-LeTech/a-plus#373]
It seems that creating courses (in my case the course instance was the one failing) is impossible as the UI is not shown for the management accounts. One could access the **/admin** portion, but that does not seem to be the right place for doing that. Creating **course instance** fails and it seems that the action for that form has not been defined.

Is there a way to use the system without Aalto Shibolleth? Can it even be used outside of Aalto University context or is that not a general purpose software?

**Comment by Mankro** [comment]
You can use it without Shibboleth. Create a super user in the command line and log in to the web app via the maintenance login form, ignoring the Shibboleth login. Create a course and then a course instance in the Django admin view (URL `/admin` like you said). You can then see the course in the app front page.

**Comment by pjotrsavitski** [comment]
Creating an instance failed miserably. The action handler did not seem to be there.

Is there any other meaningful (convenient) way apart from using Shibolleth? I did not see any way of changing the UI language (everything except **Privacy Policy** seemed to be in English only).

**Comment by Mankro** [comment]
You need to create a course before you can create a course instance (two different database tables).

**Comment by pjotrsavitski** [comment]
Done that and selected that course for the instance. Even used the one that was imported with the default test data bundle. Seems to be a code issue.

**Comment by Mankro** [comment]
That's strange. Perhaps it's easier to try it with Docker: https://github.com/apluslms/course-templates/tree/rst

**Comment by Mankro** [comment]
One thing that could fail in the creation of the course instance is that it can be picky about certain dates given in the form (such as enrollment start or life support). Leaving them empty could be the easiest solution.

**Comment by pjotrsavitski** [comment]
I was able to create an instance, when just configuring the **Starting time** and **Ending time**. I suppose that some kind of error occurred and that was not propagated to the browser due to the way I am running the instance within the VM. Did not really check the logs.

It does seem that not setting the dates, not setting something correct or just leaving some required filed unfilled results in just that behaviour. You can close the issue as I have now been able to create an instance. Although, it would be useful to have some king of instructions what is created in which order and what depends on what.

**Comment by pjotrsavitski** [comment]
Checked the logs and did find the lines when it failed. All seemed to have to deal with dates.

It also mentioned **connection refused** within context of an email module. But that one is probably due to my setup not having the email functionality being configured.

**Comment by raphendyr** [comment]
Few extra dates in course instance are not validated in the web ui, so it fails silently. just pick dates in ascending order for the fields you don't know.

In addition, use the docker as described in course-templates repo linked above. It's currently the easies solution. If you use windows, then run the containers in a VM.

Documentation in this repo is outdated, as most of it is so redundant. Gonna clean that up before the end of the year hopefully. Till then, best installation guide is the dockerfile: https://github.com/apluslms/run-aplus-front/blob/master/Dockerfile

**Comment by pjotrsavitski** [comment]
Ok. Thanks. Not using Windows, but use the VM's anyway. It is a lot more convenient, leaves no clutter lying around, allows a lot more flexibility and clean-up is rather straight forward.

**Comment by raphendyr** [comment]
True. Containers are good for that exact reason :)
