### ISSUE TITLE
I think this line shouldn't assign to let

### ISSUE THREAD

**Issue by JoonatanPartanen** [Aalto-LeTech/a-plus#409]
https://github.com/Aalto-LeTech/a-plus/blob/719f318e78328274ebaccab71dc35c3524a3af2d/exercise/static/exercise/results_staff.js#L204

This seems unintentional and might break something. Although apparently JS handles keywords and variables separately. `var let = 0;` works but `const let = 0;` doesn't (`with SyntaxError: let is disallowed as a lexically bound name`).

**Comment by Mankro** [comment]
You could make a PR to fix it (even if it is only one line :smile: ). Are there other similar issues in the code?

**Comment by JoonatanPartanen** [comment]
One thing that is a bit puzzling is the vertical scrollbar of the table. It doesn't seem to appear at all.
