### ISSUE TITLE
Course modules should support explicit ordering

### ISSUE THREAD

**Issue by ihantola** [Aalto-LeTech/a-plus#54]
Course modules (i.e. exercise rounds) should support explicit ordering instead of implicit based on closing times that is currently the only way.

A concrete use case I just hit is that my course has 6 rounds of exercises from where the last two are still open for two more weeks. I wanted to create new course module with feedback questionnaire that would close after a week. The closing time was selected because of the exam time but I would assume there are other use cases where exercise rounds are not created in linear fashion.  The problem is that the new (7th exercise round) is placed to the third last position. If you have have referred with the numbers (e.g. "6th exercise round is about javascript"), these are messed up. For students, the new exercise round is also hard to detect because of its position n the middle of the list.

**Comment by teemulehtinen** [comment]
Order is now primary sorting key. Closing time is secondary.
