### ISSUE TITLE
Admins may easily end up causing a situation where the category and the course_module of an exercise are bound to different course_instance

### ISSUE THREAD

**Issue by Rubinous** [Aalto-LeTech/a-plus#76]
Although LearningObject.clean validates that course_module and category point to the same course_instance, the course_instance of the category or the course_module can be changed later. In this case A+ might behave unexpectedly. For example this would cause inconsistency of the points in the view_instance view.

One way to fix this would be to not allow updates to the course_instance field of LearningObjectCategory and Course module in case they have any exercises bound to them.

However in sometimes, teachers or administrators may want to throw exercises from one course instance to another by throwing the whole category or course module to another instance. I think this wouldn't be possible with the suggested fix.

Ideas?

**Comment by teemulehtinen** [comment]
Validation prevents.
