### ISSUE TITLE
Users can only submit files with relatively short file names

### ISSUE THREAD

**Issue by Rubinous** [Aalto-LeTech/a-plus#77]
The FileField file_object in SubmittedFile model of exercise.submission_models max_length 100 (as default). This does not even mean that the file that the user submits may have a name of 100 characters because the relative path is added to the file name and that is what is going to be saved in the database.

In addition to that, there is a Django ticket related to the FileField's max_length attribute https://code.djangoproject.com/ticket/11027.

**Comment by teemulehtinen** [comment]
Any file names are sanitized and limited to 80 chars which will fit in the current 255 path.
