### ISSUE TITLE
Too wide label area in form.

### ISSUE THREAD

**Issue by raphendyr** [Aalto-LeTech/a-plus#81]
With questionnaire it's common to select wrong answer when focusing window as label is block element (all way to the right of the center container). Also clicking the questions selects the first answer (I ques this is for file submissions?).

For questionnaires the answer block line should be colored or in some way visualized to tell user to not click on white area. Or set label only to the answer text.

**Comment by teemulehtinen** [comment]
These issues are fixed on the mooc-grader. Anyway this is a grader issue not A+.
