### ISSUE TITLE
User vs UserProfile

### ISSUE THREAD

**Issue by Rubinous** [Aalto-LeTech/a-plus#94]
Fields like Submission.submitters and CourseInstance.assistants are related to the UserProfile model. Many methods take UserProfile as argument for identifying the user but there are also methods and classes (for example CourseSummary) that take the User model as argument instead. I think that the should be unified. I would suggest changing everything to use UserProfile and use User only when explicitly needed, but, as I hope A+ will some day run on Django 1.5+, where some of the aspects related to UserProfile are deprecated, this may not be the way to go. So some thinking is required here.

**Comment by teemulehtinen** [comment]
Model relations are still to user profiles. Most of this hassle is now covered by centralized access control and refactored methods. Lets see if this becomes troublesome again in future. Fixing would be non straight forward migration.
